name: Run Unit Tests on Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Get Summary
        id: test
        run: |
          output=$(npx mocha tests.js --reporter spec)
          echo "$output"

      - name: Extract Test Summary
        run: |
          passed=$(echo "$output" | grep "1 passing" | awk '{print $1}')
          failed=$(echo "$output" | grep "1 failing" | awk '{print $1}')
          echo "Passed: $passed"
          echo "Failed: $failed"
